[settings]
experimental = true

[tools]
atuin = "18.12.1"
bun = "1.3.9"
delta = "0.18.2"
fzf = "0.68.0"
node = "25.6.1"
starship = "1.24.2"
vivid = "0.10.1"
zoxide = "0.9.9"
difftastic = "0.67.0"
fd = "10.3.0"
github-cli = "2.87.2"
gum = "0.17.0"
jless = "0.9.0"
jq = "1.8.1"
lsd = "1.2.0"
ripgrep = "15.1.0"
uv = "0.10.4"
yq = "4.52.4"
